blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
   url(r'^$',views.Index,name='index'),
]

metablog/urls.py
from django.conf.urls import url,include
from django.views.generic import TemplateView

from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.db import models

class Reporter(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()

    def __str__(self):              # __unicode__ on Python 2
        return "%s %s" % (self.first_name, self.last_name)

class Article(models.Model):
    headline = models.CharField(max_length=100)
    pub_date = models.DateField()
    reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE)
    

    def __str__(self):              # __unicode__ on Python 2
        return self.headline

    class Meta:
        ordering = ('headline',)
        
        
        
class Book(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)

class Paragraph(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=100)
    book = models.ManyToManyField(Book)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)
# Create your models here.

blog/views.py
from django.shortcuts import render

from .models import Article,Reporter,Paragraph,Book

def Index(request):
    a = Article.objects.all()
    b = Reporter.objects.all()
    c = Book.objects.all()
    d = Paragraph.objects.all()
    
    context  = {
        'article' : a,
        'reporter' : b,
        'book' : c,
        'paragraph' : d,
    }
    return render(request,'test.html',context)

# Create your views here.

templates/test.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <link href="https://fonts.googleapis.com/css?family=Oswald:300|Roboto+Condensed" rel="stylesheet">
    <style>
        body {
            /*font-family: 'Oswald', sans-serif;*/
            font-family: 'Roboto Condensed', sans-serif;

        }

        .plus {
            margin-top: 28vh;
            margin-left: 40%;
            font-size: 70px;
        }

        .img {
            height: 60vh!important;
            width: 100%;
        }

        .pager {
            margin-top: 50vh;
            position: fixed;
            margin-left: 4%;
            color: black;

        }

        .popover {
            width: 100%;

        }

        .detail-post {
            margin-top: 5%;
        }

        .heart {
            color: red;
            font-size: 20px;
        }

    </style>
</head>

<body>

    <nav class="navbar navbar-fixed-top navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
                <a class="navbar-brand" href="">MetaBlog</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="">Home</a></li>
                    <li><a href="">Menu</a></li>

                    <li><a href="#" data-toggle="modal" data-target="#myModal">&nbsp;<span class="glyphicon glyphicon-plus"></span></a></li>
                    <li class="text-center"><a href="#" data-toggle="modal" data-target="#myModal"> Page 2 of 5</a></li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=""><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                    <li><a href=""><span class="glyphicon glyphicon-log-in"></span> Login</a></li>


                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class=" glyphicon glyphicon-cog"></span>
                          <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="">My Profile</a></li>
                            <li><a href="">My Drafs</a></li>
                            <li class="divider"></li>
                            <li><a href=""><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                        </ul>
                    </li>
                </ul>

            </div>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <br>


            <div class="col-md-12">
                <div class="col-md-2">
                  
                </div>
                <div class="col-md-8 detail-post">

                    <div class="thumbnail">
                        <div class="caption">
                            <h2>Foreignkey Forward Relation</h2>
                            {% for detail in article %}

                            <h4> {{ detail.id }}: {{ detail.headline }} ||<span class="glyphicon glyphicon-user">{{ detail.reporter }}</span></h4>

                            {% endfor %}


                        </div>
                        <hr>
                        <hr>

                        <div class="caption">
                            <h2>Foreignkey Backward/Reverse Relation</h2>
                            {% for data1 in reporter %}


                            <h3>{{ data1.id }}:<span class="glyphicon glyphicon-user"></span>Reporter: {{ data1.first_name }}

                            </h3>

                            {% for data2 in data1.article_set.all %} {{ data2.id }} : {{ data2.headline }} <br> {% endfor%} {% endfor %}



                        </div>
                        <hr>
                        <hr>

                        <div class="caption">
                            <h2>ManyToMany Backward/Reverse Relation</h2>

                            {% for data1 in book%}
                            <b>No. {{ data1.id }}: Book Name:</b> {{ data1.title }} <br>
                               
                               {% for data2 in data1.paragraph_set.all %} <b>Paragraphs {{ data2.id }}:</b> {{ data2.title }} <br> {% endfor%}
                                <hr>
                            {% endfor%}


                        </div>
                        
                        
                        <div class="caption">
                            <h2>ManyToMany Forward Relation</h2>

                            {% for data1 in paragraph.all %}
                                <b>{{ data1.id }}) Paragraph Name:</b> {{ data1.title }} || <b>Books:</b>
                                
                          
                              {% for data3 in data1.book.all %}<b>No.</b>{{ data3.id }} {{ data3 }} {% endfor%} <br>
                        
                           
                                <hr>
                            {% endfor%}
                            


                        </div>



                    </div>
                </div>
                <div class="col-md-2">

                   
                </div>
            </div>










            <!--Post Create Modal-->

            <div class="col-md-12">
                <div class="modal fade" id="myModal" role="dialog">
                    <div class="modal-dialog modal-lg">

                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Add Post</h4>
                            </div>
                            <div class="modal-body">
                                <form class="form-horizontal" action="/action_page.php">
                                    <div class="form-group">
                                        <label class="control-label col-sm-2" for="email">Add Title:</label>
                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" id="email" placeholder="Add Title" name="email">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-sm-2" for="pwd">Add Content</label>
                                        <div class="col-sm-10">
                                            <input type="textarea" class="form-control" id="pwd" placeholder="Add Content" name="pwd">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                            <div class="checkbox">
                                                <label><input type="checkbox" name="remember"> Save As Draft</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                            <button type="submit" class="btn btn-default">Submit</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>



        </div>
    </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('[data-toggle="popover"]').popover({
            placement: 'top',
            trigger: 'hover',
            container: 'body'
        });
    });

</script>

</html>